apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:289835835122:certificate/a1098d2b-0692-4860-8d2b-a8615f20efdd

    alb.ingress.kubernetes.io/actions.blue-green: >
      {
        "type": "forward",
        "forwardConfig": {
          "targetGroups": [
            {
              "serviceName": "service-blue",
              "servicePort": "8080",
              "weight": 0
            },
            {
              "serviceName": "service-green",
              "servicePort": "8080",
              "weight": 100
            }
          ]
        }
      }

spec:
  ingressClassName: alb

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blue-green
            port:
              name: use-annotation
